version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=ginblog
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ginblog
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local